#!/bin/bash

if [ -r "../.cookie" ]; then
  source "../.cookie"
fi

export TZ=CET
thisyear="$(date +%Y)"
thismonth="$(date +%m)"
thisday="$(date +%d)"

year=2020

if [ "$thisyear" -ne "$year" -o "$thismonth" -ne 12 -o "$thisday" -lt 26 ]; then
    echo "Not a valid date: $thisday / $thismonth / $thisyear"
    exit 0
fi

filename="../data/day$thisday".in

if [ -r "$filename" ]; then
    echo "Filename $filename already exists!"
    exit 0
fi

curl -sS -o "$filename" -b "$AOC_COOKIE" https://adventofcode.com/"$year"/day/"$day"/input
echo "Curled into $filename"