#!/bin/bash

## ghcid -c "stack ghci --main-is aoc2024:exe:aoc2024-exe" --test="Day${1}.main"

# export PATH=$(stack path --compiler-bin --silent):$PATH

ghciwatch --command "stack repl" --test-ghci="Day${1}.main"
